(function (root) {
  root.TacticalData = {
    operation: {
      title: 'Операция «Сухой овраг»',
      phase: 'Разведка перед рубежом',
      weather: 'Облачно · ветер 3 м/с',
      connection: 'Связь устойчива',
    },
    squad: {
      id: 'alpha',
      name: '1-е отделение',
      callsign: 'Альфа',
      commanderId: 'alpha-1',
      task: 'Занять высоту 117 и вести наблюдение',
    },
    units: [
      {
        id: 'alpha-1',
        name: 'Барс',
        number: '1',
        role: 'Командир отделения',
        group: 'Альфа',
        x: 58.7,
        y: 43.5,
        heading: 18,
        state: 'normal',
        action: 'Наблюдает сектор',
        order: 'Удерживать высоту 117',
        posture: 'crouched',
        movement: 'careful',
        health: 100,
        morale: 86,
        fatigue: 12,
        stress: 8,
        suppression: 4,
        ammo: 28,
        ammoMax: 30,
        weapon: 'АК-74М',
        secondary: 'РГД-5 × 2',
        detection: 'Скрыт',
        visibility: 'Видит 2 контакта',
        statusText: 'Готов к приказу',
        unavailablePostures: [],
        tags: ['командир', 'радиостанция'],
      },
      {
        id: 'alpha-2',
        name: 'Кедр',
        number: '2',
        role: 'Стрелок',
        group: 'Альфа',
        x: 56.8,
        y: 13.2,
        heading: 163,
        state: 'executing',
        action: 'Движется к укрытию',
        order: 'Скрытно выйти к лесу',
        posture: 'standing',
        movement: 'normal',
        health: 100,
        morale: 78,
        fatigue: 24,
        stress: 18,
        suppression: 10,
        ammo: 24,
        ammoMax: 30,
        weapon: 'АК-74М',
        secondary: 'РГД-5 × 1',
        detection: 'Не обнаружен',
        visibility: 'Целей не видит',
        statusText: 'Выполняет приказ',
        unavailablePostures: [],
        tags: ['стрелок'],
      },
      {
        id: 'alpha-3',
        name: 'Сокол',
        number: '3',
        role: 'Пулемётчик',
        group: 'Альфа',
        x: 39.5,
        y: 65.4,
        heading: 43,
        state: 'suppressed',
        action: 'Прижат огнём',
        order: 'Подавить противника у дома',
        posture: 'prone',
        movement: 'careful',
        health: 88,
        morale: 61,
        fatigue: 46,
        stress: 72,
        suppression: 68,
        ammo: 74,
        ammoMax: 100,
        weapon: 'РПК-74',
        secondary: 'РГД-5 × 1',
        detection: 'Обнаружен',
        visibility: 'Видит 1 контакт',
        statusText: 'Сильное подавление',
        unavailablePostures: ['standing'],
        tags: ['пулемётчик', 'подавлен'],
      },
      {
        id: 'alpha-4',
        name: 'Док',
        number: '4',
        role: 'Санитар-стрелок',
        group: 'Альфа',
        x: 27.4,
        y: 37.2,
        heading: 92,
        state: 'wounded',
        action: 'Оказывает самопомощь',
        order: 'Следовать за командиром',
        posture: 'crouched',
        movement: 'careful',
        health: 64,
        morale: 72,
        fatigue: 31,
        stress: 49,
        suppression: 26,
        ammo: 16,
        ammoMax: 30,
        weapon: 'АКС-74У',
        secondary: 'Аптечка × 3',
        detection: 'Подозрение',
        visibility: 'Целей не видит',
        statusText: 'Ранение ноги',
        unavailablePostures: ['prone'],
        tags: ['санитар', 'ранен'],
      },
      {
        id: 'alpha-5',
        name: 'Гранит',
        number: '5',
        role: 'Старший стрелок',
        group: 'Альфа',
        x: 75.8,
        y: 68.4,
        heading: 311,
        state: 'firing',
        action: 'Ведёт огонь',
        order: 'Огонь по подтверждённой цели',
        posture: 'crouched',
        movement: 'normal',
        health: 96,
        morale: 82,
        fatigue: 38,
        stress: 44,
        suppression: 18,
        ammo: 9,
        ammoMax: 30,
        weapon: 'АК-74М',
        secondary: 'РПГ-26 × 1',
        detection: 'Обнаружен',
        visibility: 'Видит 1 контакт',
        statusText: 'Ведёт прицельный огонь',
        unavailablePostures: [],
        tags: ['стрелок', 'ведёт огонь'],
      },
      {
        id: 'alpha-6',
        name: 'Ручей',
        number: '6',
        role: 'Гранатомётчик',
        group: 'Альфа',
        x: 20.2,
        y: 78.7,
        heading: 8,
        state: 'offline',
        action: 'Ожидает',
        order: 'Нет подтверждённого приказа',
        posture: 'standing',
        movement: 'normal',
        health: 100,
        morale: 74,
        fatigue: 19,
        stress: 11,
        suppression: 0,
        ammo: 30,
        ammoMax: 30,
        weapon: 'АК-74М',
        secondary: 'РПГ-7В2 · 3 выстрела',
        detection: 'Неизвестно',
        visibility: 'Данные устарели',
        statusText: 'Вне устойчивой связи',
        unavailablePostures: [],
        tags: ['гранатомётчик', 'нет связи'],
      },
    ],
    enemies: [
      { id: 'enemy-1', type: 'confirmed', x: 83.5, y: 31.5, heading: 225, label: 'Стрелок', confidence: 100 },
      { id: 'enemy-2', type: 'confirmed', x: 67.2, y: 20.4, heading: 191, label: 'Пулемёт', confidence: 92 },
      { id: 'enemy-3', type: 'suspected', x: 48.2, y: 81.5, heading: 0, label: 'Шум', confidence: 46 },
      { id: 'enemy-4', type: 'last-known', x: 87.5, y: 63.5, heading: 0, label: 'Последнее место', confidence: 71 },
    ],
    postures: [
      { id: 'standing', label: 'Стоя', hint: 'Максимальная скорость и обзор. Высокая заметность.', exposure: 'высокая', icon: 'standing' },
      { id: 'crouched', label: 'Пригнувшись', hint: 'Меньше заметность, умеренная скорость и хороший обзор.', exposure: 'средняя', icon: 'crouched' },
      { id: 'prone', label: 'Лёжа', hint: 'Минимальная заметность и профиль. Медленное перемещение.', exposure: 'низкая', icon: 'prone' },
    ],
    movements: [
      { id: 'careful', label: 'Осторожно', speed: '0,7 м/с', noise: 'низкий', fatigue: '+', observation: 'высокая' },
      { id: 'normal', label: 'Шагом', speed: '1,4 м/с', noise: 'средний', fatigue: '+', observation: 'обычная' },
      { id: 'fast', label: 'Быстро', speed: '2,5 м/с', noise: 'высокий', fatigue: '++', observation: 'снижена' },
      { id: 'run', label: 'Бегом', speed: '4,2 м/с', noise: 'очень высокий', fatigue: '+++', observation: 'низкая' },
    ],
    layers: [
      { id: 'danger', label: 'Опасность', shortcut: '1', description: 'Направления и плотность известных угроз.', tone: 'red' },
      { id: 'concealment', label: 'Скрытность', shortcut: '2', description: 'Участки, снижающие вероятность обнаружения.', tone: 'green' },
      { id: 'visibility', label: 'Видимость', shortcut: '3', description: 'Сектор и качество обзора выбранного бойца.', tone: 'blue' },
      { id: 'routeCost', label: 'Стоимость пути', shortcut: '4', description: 'Суммарная цена движения по местности.', tone: 'amber' },
      { id: 'cover', label: 'Укрытия', shortcut: '5', description: 'Места с физической защитой от огня.', tone: 'cyan' },
      { id: 'positions', label: 'Тактические позиции', shortcut: '6', description: 'Подходящие точки наблюдения и огня.', tone: 'violet' },
      { id: 'noise', label: 'Шум', shortcut: '7', description: 'Оценка слышимости действий и движения.', tone: 'orange' },
    ],
    demoEvents: [
      { level: 'info', title: 'Противник обнаружен', body: 'Барс подтвердил цель у восточного дома.' },
      { level: 'warning', title: 'Боец подавлен', body: 'Сокол временно не может подняться в полный рост.' },
      { level: 'critical', title: 'Получен огонь', body: 'Выстрелы с северо-востока. Направление отмечено на карте.' },
      { level: 'success', title: 'Приказ принят', body: 'Маршрут передан отделению.' },
      { level: 'warning', title: 'Мало боеприпасов', body: 'У Гранита осталось меньше одного магазина.' },
      { level: 'info', title: 'Цель потеряна', body: 'Показано последнее известное место.' },
    ],
  };
})(typeof globalThis !== 'undefined' ? globalThis : this);
